# Generated by Django 4.2.7 on 2023-12-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200)),
                ('d_phone', models.CharField(max_length=10)),
                ('d_b_group', models.CharField(max_length=3)),
                ('d_quantity', models.PositiveIntegerField()),
                ('d_date', models.DateField()),
                ('d_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_b_group', models.CharField(max_length=3)),
                ('p_add', models.CharField(max_length=300)),
                ('p_gender', models.CharField(max_length=6)),
                ('p_age', models.PositiveIntegerField()),
                ('p_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='receive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200)),
                ('r_phone', models.CharField(max_length=10)),
                ('r_b_group', models.CharField(max_length=3)),
                ('r_quantity', models.PositiveIntegerField()),
                ('r_date', models.DateField()),
                ('r_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_group', models.CharField(max_length=3)),
                ('b_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
