# Generated by Django 4.2.7 on 2023-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_person_p_add_alter_person_p_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='r_date',
        ),
        migrations.AddField(
            model_name='donor',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
    ]
