# Generated by Django 4.2.7 on 2023-12-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_remove_receive_r_date_donor_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='p_id',
            field=models.IntegerField(),
        ),
    ]
